# Internal Audit Data Analytics & Exception Detection

## 1. Data Understanding

### Objective

The objective of this project is to use data analytics to support internal audit testing by identifying unusual transactions, potential control exceptions, and areas requiring further investigation.

This notebook focuses on understanding and validating the underlying banking transaction data before performing audit testing.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
transactions = pd.read_csv(
    "../data/raw/banking_transactions.csv",
    parse_dates=["Transaction_Date"]
)

employees = pd.read_csv(
    "../data/raw/employee_master.csv"
)

vendors = pd.read_csv(
    "../data/raw/vendor_master.csv"
)

thresholds = pd.read_csv(
    "../data/raw/approval_thresholds.csv"
)

In [3]:
transactions.head()

,Transaction_ID,Transaction_Date,Account_ID,Employee_ID,Branch,Transaction_Type,Amount_EUR,Approval_Status,Approver_ID,Channel,Vendor_ID
0,TX100000,2025-02-02 11:00:00,AC318113,EMP1115,Dublin,Direct Debit,48.87,Pending,APR5038,ATM,VEN20015
1,TX100001,2025-10-09 18:00:00,AC315623,EMP1028,Galway,Cash Withdrawal,47.50,Pending,APR5022,Mobile,VEN20152
2,TX100002,2025-08-27 06:00:00,AC311833,EMP1072,Waterford,Vendor Payment,20.45,Pending,APR5036,Corporate,VEN20008
3,TX100003,2025-06-09 18:00:00,AC318220,EMP1105,Galway,Vendor Payment,101.05,Approved,APR5047,Online,VEN20054
4,TX100004,2025-06-07 15:00:00,AC318216,EMP1007,Cork,Bank Transfer,159.96,Approved,APR5038,Online,VEN20222

In [4]:
transactions.shape

(60450, 11)

In [5]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 60450 entries, 0 to 60449
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    60450 non-null  str
 1   Transaction_Date  60450 non-null  datetime64[us]
 2   Account_ID        60450 non-null  str
 3   Employee_ID       60450 non-null  str
 4   Branch            60450 non-null  str
 5   Transaction_Type  60450 non-null  str
 6   Amount_EUR        60450 non-null  float64
 7   Approval_Status   60450 non-null  str
 8   Approver_ID       60450 non-null  str
 9   Channel           60450 non-null  str
 10  Vendor_ID         60450 non-null  str
dtypes: datetime64[us](1), float64(1), str(9)
memory usage: 5.1 MB

In [6]:
transactions.describe()

                 Transaction_Date    Amount_EUR
count                       60450  60450.000000
mean   2025-07-01 20:52:26.019851    329.777475
min           2025-01-01 00:00:00      1.000000
25%           2025-04-01 18:15:00     27.130000
50%           2025-07-02 01:00:00     55.035000
75%           2025-09-30 16:00:00    113.040000
max           2025-12-31 00:00:00  44976.710000
std                           NaN   2707.252059

In [7]:
transactions.isnull().sum()

Transaction_ID      0
Transaction_Date    0
Account_ID          0
Employee_ID         0
Branch              0
Transaction_Type    0
Amount_EUR          0
Approval_Status     0
Approver_ID         0
Channel             0
Vendor_ID           0
dtype: int64

In [8]:
transactions.nunique()

Transaction_ID      60450
Transaction_Date     9011
Account_ID          18993
Employee_ID           120
Branch                  6
Transaction_Type        5
Amount_EUR          21866
Approval_Status         3
Approver_ID           178
Channel                 5
Vendor_ID             500
dtype: int64