# Internal Audit Data Analytics & Exception Detection

## 2. Data Quality

### Objective

The objective of this section is to assess the completeness, consistency,
validity and integrity of the transaction data before performing internal
audit testing.

In [1]:
import pandas as pd
import numpy as np

In [2]:
transactions = pd.read_csv(
    "../data/raw/banking_transactions.csv",
    parse_dates=["Transaction_Date"]
)

employees = pd.read_csv(
    "../data/raw/employee_master.csv"
)

vendors = pd.read_csv(
    "../data/raw/vendor_master.csv"
)

thresholds = pd.read_csv(
    "../data/raw/approval_thresholds.csv"
)

In [ ]:
#Duplicate Transaction IDs
transactions["Transaction_ID"].duplicated().sum()

np.int64(0)

In [5]:
transactions[
    transactions["Transaction_ID"].duplicated(keep=False)
].sort_values("Transaction_ID").head(20)

Empty DataFrame
Columns: [Transaction_ID, Transaction_Date, Account_ID, Employee_ID, Branch, Transaction_Type, Amount_EUR, Approval_Status, Approver_ID, Channel, Vendor_ID]
Index: []

In [23]:
#Exact Duplicate Records
transactions.duplicated().sum()

np.int64(0)

In [7]:
transactions[
    transactions.duplicated(keep=False)
].head(20)

Empty DataFrame
Columns: [Transaction_ID, Transaction_Date, Account_ID, Employee_ID, Branch, Transaction_Type, Amount_EUR, Approval_Status, Approver_ID, Channel, Vendor_ID]
Index: []

In [ ]:

#Missing Values
missing = transactions.isnull().sum()

missing[missing > 0]

Series([], dtype: int64)

In [ ]:
#Validate Categorical Values
transactions["Transaction_Type"].unique()

<StringArray>
[   'Direct Debit', 'Cash Withdrawal',  'Vendor Payment',   'Bank Transfer',
    'Card Payment']
Length: 5, dtype: str

In [10]:
transactions["Approval_Status"].unique()

<StringArray>
['Pending', 'Approved', 'Rejected']
Length: 3, dtype: str

In [11]:
transactions["Channel"].unique()

<StringArray>
['ATM', 'Mobile', 'Corporate', 'Online', 'Branch']
Length: 5, dtype: str

In [12]:
transactions["Branch"].unique()

<StringArray>
['Dublin', 'Galway', 'Waterford', 'Cork', 'Kilkenny', 'Limerick']
Length: 6, dtype: str

In [ ]:
#Transaction Amount Validation
transactions["Amount_EUR"].describe()

count    60450.000000
mean       329.777475
std       2707.252059
min          1.000000
25%         27.130000
50%         55.035000
75%        113.040000
max      44976.710000
Name: Amount_EUR, dtype: float64

In [14]:
(transactions["Amount_EUR"] <= 0).sum()

np.int64(0)

In [15]:
transactions[
    transactions["Amount_EUR"] <= 0
]

Empty DataFrame
Columns: [Transaction_ID, Transaction_Date, Account_ID, Employee_ID, Branch, Transaction_Type, Amount_EUR, Approval_Status, Approver_ID, Channel, Vendor_ID]
Index: []

In [16]:
transactions.nlargest(
    20, 
    "Amount_EUR"
)[
    ["Transaction_ID", "Transaction_Date", "Transaction_Type", "Amount_EUR"]
]

      Transaction_ID    Transaction_Date Transaction_Type  Amount_EUR
28847       TX128847 2025-12-09 22:00:00     Card Payment    44976.71
26958       TX126958 2025-03-01 20:00:00    Bank Transfer    44955.09
30926       TX130926 2025-03-23 21:00:00     Card Payment    44787.60
5946        TX105946 2025-04-06 22:00:00  Cash Withdrawal    44639.00
60104       TX160104 2025-04-06 22:02:00  Cash Withdrawal    44639.00
51015       TX151015 2025-11-30 08:00:00     Card Payment    44553.19
14404       TX114404 2025-11-16 23:00:00     Card Payment    44379.74
7147        TX107147 2025-06-12 06:00:00    Bank Transfer    44153.11
22041       TX122041 2025-06-06 19:00:00  Cash Withdrawal    44007.07
31813       TX131813 2025-07-26 18:00:00     Card Payment    43845.76
30434       TX130434 2025-04-19 00:00:00  Cash Withdrawal    43777.01
13621       TX113621 2025-03-03 03:00:00    Bank Transfer    43741.67
2357        TX102357 2025-03-21 19:00:00    Bank Transfer    43722.43
49883       TX149883 2025-07-11 23:00:00     Card Payment    43718.49
5129        TX105129 2025-08-08 20:00:00    Bank Transfer    43585.39
23000       TX123000 2025-10-07 11:00:00     Card Payment    43552.48
46471       TX146471 2025-01-12 07:00:00     Card Payment    43529.01
45789       TX145789 2025-06-13 18:00:00    Bank Transfer    43513.45
24136       TX124136 2025-01-16 18:00:00    Bank Transfer    43443.38
20159       TX120159 2025-09-17 20:00:00     Card Payment    43368.29

In [ ]:
#Date & Time Validation
transactions["Transaction_Date"].min()

Timestamp('2025-01-01 00:00:00')

In [18]:
transactions["Transaction_Date"].max()

Timestamp('2025-12-31 00:00:00')

In [19]:
transactions["Transaction_Date"].is_monotonic_increasing

False

In [ ]:
#Referential Integrity
invalid_employees = transactions[
    ~transactions["Employee_ID"].isin(employees["Employee_ID"])
]

invalid_employees.shape

(0, 11)

In [21]:
invalid_vendors = transactions[
    ~transactions["Vendor_ID"].isin(vendors["Vendor_ID"])
]

invalid_vendors.shape

(0, 11)

Data Quality Conclusion

The transaction dataset was assessed for completeness, uniqueness,
validity and referential integrity.